"""
report.py – Auto-generate engineering report (Markdown)
"""

from __future__ import annotations
from datetime import datetime
from pathlib import Path
from typing import Optional

from .geometry import RectangularCantilever, CircularCantilever
from .solver import StressCycle
from .fatigue import FatigueResult, MaterialFatigue


def generate_markdown_report(
    geometry,
    material: MaterialFatigue,
    cycle: StressCycle,
    result: FatigueResult,
    *,
    E: float,
    F_a: float,
    R: float,
    method: str,
    N_design: float,
    project_title: str = "Flexure Fatigue Analysis",
    author: str = "ZMatrix253",
    company: str = "",
) -> str:
    """
    Generate a self-contained Markdown engineering report.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Geometry description
    if isinstance(geometry, RectangularCantilever):
        geo_desc = (
            f"- Type: Rectangular cantilever leaf spring\n"
            f"- Length L = {geometry.L*1000:.1f} mm\n"
            f"- Width b = {geometry.b*1000:.1f} mm\n"
            f"- Thickness h = {geometry.h*1000:.1f} mm\n"
            f"- Second moment of area I = {geometry.I:.3e} m⁴"
        )
        geo_type = "Rectangular cantilever"
    else:
        geo_desc = (
            f"- Type: Circular cross-section cantilever\n"
            f"- Length L = {geometry.L*1000:.1f} mm\n"
            f"- Diameter d = {geometry.d*1000:.1f} mm\n"
            f"- Second moment of area I = {geometry.I:.3e} m⁴"
        )
        geo_type = "Circular cantilever"

    pass_fail = "PASS" if result.N_f >= N_design else "FAIL"

    report = f"""# {project_title}

**Date:** {now}  
**Author:** {author}  
{f"**Company:** {company}" if company else ""}

---

## 1. Executive Summary

| Item                    | Value                          |
|-------------------------|--------------------------------|
| Geometry                | {geo_type}                     |
| Analysis method         | {method.capitalize()}          |
| Force amplitude F_a     | {F_a:.1f} N                    |
| R-ratio                 | {R}                            |
| Predicted life N_f      | {result.N_f:.3e} cycles        |
| Target life N_design    | {N_design:.0e} cycles          |
| Safety factor (life)    | {result.safety_factor_life:.2f}|
| **Result**              | **{pass_fail}**                |

---

## 2. Geometry

{geo_desc}

---

## 3. Material Properties

| Property              | Value          |
|-----------------------|----------------|
| Young's modulus E     | {E/1e9:.0f} GPa |
| Fatigue strength coeff. σ_f' | {material.sigma_f_prime/1e6:.0f} MPa |
| Basquin exponent b    | {material.b}   |
| Ultimate strength σ_uts | {material.sigma_uts/1e6:.0f} MPa |

---

## 4. Loading

- Cyclic tip force (constant amplitude)
- Force amplitude F_a = {F_a:.1f} N
- Load ratio R = F_min / F_max = {R}
- Fully reversed: {"Yes" if abs(R + 1) < 1e-9 else "No"}

---

## 5. Analysis Assumptions

- Euler-Bernoulli beam theory
- Material model: linear elastic only
- {"Large-deflection (elastica) geometric nonlinearity included" if method == "nonlinear" else "Small-deflection (linear) theory"}
- Constant amplitude loading (no spectrum / rainflow)
- Uniaxial bending stress only
- Goodman mean-stress correction
- Basquin stress-life (S-N) approach
- No plasticity, no stress concentrations, no surface finish factors

---

## 6. Stress Results

| Quantity     | Value            |
|--------------|------------------|
| σ_max        | {cycle.sigma_max/1e6:.2f} MPa |
| σ_min        | {cycle.sigma_min/1e6:.2f} MPa |
| σ_a (amplitude) | {cycle.sigma_a/1e6:.2f} MPa |
| σ_m (mean)   | {cycle.sigma_m/1e6:.2f} MPa |
| σ_ar (Goodman equivalent) | {result.sigma_ar/1e6:.2f} MPa |

---

## 7. Fatigue Results

| Quantity                  | Value                    |
|---------------------------|--------------------------|
| Estimated cycles to failure N_f | {result.N_f:.3e}   |
| Target design life        | {N_design:.0e}           |
| Safety factor on life     | {result.safety_factor_life:.2f} |
| Safety factor on stress   | {result.safety_factor_stress:.2f} |
| **Assessment**            | **{pass_fail}**          |

---

## 8. Limitations & Notes

- Results are valid only within the stated assumptions.
- No safety factors for surface finish, size, reliability, or temperature are applied.
- Large-deflection solution assumes inextensible centreline and pure bending.
- This tool is intended for early-stage design estimates, not final certification.
- Always cross-check critical designs with detailed FEA and/or testing.

---

*Report generated by Flexure Fatigue Estimator (FFE)*
"""
    return report


def save_report(report_md: str, path: str | Path) -> Path:
    """Save Markdown report to disk."""
    path = Path(path)
    path.write_text(report_md, encoding="utf-8")
    return path